/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.util.Date;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.JFrame.EXIT_ON_CLOSE;

/**
 *
 * @author MAESTRO
 */
public class Navigation extends javax.swing.JFrame {
    Connection conn = null;
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    PreparedStatement pst1 = null;
    ResultSet rs1 = null;
    
    PreparedStatement pst2 = null;
    ResultSet rs2 = null;
    
    PreparedStatement pst3 = null;
    ResultSet rs3 = null;
    
    String l = Login.Acc;
    public static int acid;
    
        
        

    /**
     * Creates new form Navigation
     */
    public Navigation() {
        initComponents();
        try {
            
            
            conn = MySqlConnect.ConnectDB();
            String sql = "Select * from account_details where accountNo='"+l+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String fname = rs.getString("FirstName");
                String sname = rs.getString("SecondName");
                String accno = rs.getString("accountNo");
                String phone = rs.getString("phone");
                
                txtAccNo.setText(accno);
                txtName.setText(fname + " " + sname);
                txtPhone.setText(phone);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
                conn = MySqlConnect.ConnectDB();
                String sql = "Select id from account_details where accountNo='"+l+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                if(rs.next()){
                     acid = rs.getInt("id");
                }
}catch(SQLException e){
    
}
        
    }
    String active = "home";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        property_panel = new javax.swing.JPanel();
        ministatement = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        withdraw = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        transfer = new javax.swing.JPanel();
        TRANSFER = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        import_home = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtBalance = new javax.swing.JTextField();
        btnBalance = new javax.swing.JButton();
        txtAccNo2 = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAccNo = new javax.swing.JTextField();
        txtAccNo3 = new javax.swing.JTextField();
        txtAccNo4 = new javax.swing.JTextField();
        import_withdraw = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        txtwithdraw = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        import_transfer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        frmAccount = new javax.swing.JTextField();
        toAccount = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        import_ministatement = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btnprint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        property_panel.setBackground(new java.awt.Color(0, 51, 102));

        ministatement.setBackground(new java.awt.Color(0, 51, 51));
        ministatement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ministatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ministatementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ministatementMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ministatementMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MINI STATEMENT");

        javax.swing.GroupLayout ministatementLayout = new javax.swing.GroupLayout(ministatement);
        ministatement.setLayout(ministatementLayout);
        ministatementLayout.setHorizontalGroup(
            ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ministatementLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ministatementLayout.setVerticalGroup(
            ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ministatementLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        withdraw.setBackground(new java.awt.Color(0, 51, 51));
        withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                withdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                withdrawMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                withdrawMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WITHDRAW");

        javax.swing.GroupLayout withdrawLayout = new javax.swing.GroupLayout(withdraw);
        withdraw.setLayout(withdrawLayout);
        withdrawLayout.setHorizontalGroup(
            withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        withdrawLayout.setVerticalGroup(
            withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        home.setBackground(new java.awt.Color(0, 51, 51));
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        home.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOME");
        home.add(jLabel3);
        jLabel3.setBounds(36, 24, 115, 23);

        transfer.setBackground(new java.awt.Color(0, 51, 51));
        transfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transferMousePressed(evt);
            }
        });

        TRANSFER.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 18)); // NOI18N
        TRANSFER.setForeground(new java.awt.Color(255, 255, 255));
        TRANSFER.setText("TRANSFER");

        javax.swing.GroupLayout transferLayout = new javax.swing.GroupLayout(transfer);
        transfer.setLayout(transferLayout);
        transferLayout.setHorizontalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TRANSFER, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transferLayout.setVerticalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TRANSFER)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout property_panelLayout = new javax.swing.GroupLayout(property_panel);
        property_panel.setLayout(property_panelLayout);
        property_panelLayout.setHorizontalGroup(
            property_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ministatement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        property_panelLayout.setVerticalGroup(
            property_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, property_panelLayout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ministatement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UBIQUITTI BANK ATM");

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        main.setLayout(null);

        import_home.setBackground(new java.awt.Color(255, 153, 0));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBalance.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtBalance.setEnabled(false);

        btnBalance.setBackground(new java.awt.Color(51, 51, 255));
        btnBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnBalance.setText("BALANCE");
        btnBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBalance.setBorderPainted(false);
        btnBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBalanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBalanceMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        txtAccNo2.setEditable(false);
        txtAccNo2.setBackground(new java.awt.Color(255, 153, 0));
        txtAccNo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAccNo2.setText("ACCOUNT NUMBER:");
        txtAccNo2.setBorder(null);
        txtAccNo2.setOpaque(false);

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 153, 0));
        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.setOpaque(false);

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(255, 153, 0));
        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setBorder(null);
        txtPhone.setOpaque(false);

        txtAccNo.setEditable(false);
        txtAccNo.setBackground(new java.awt.Color(255, 153, 0));
        txtAccNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAccNo.setForeground(new java.awt.Color(255, 255, 255));
        txtAccNo.setBorder(null);
        txtAccNo.setOpaque(false);

        txtAccNo3.setEditable(false);
        txtAccNo3.setBackground(new java.awt.Color(255, 153, 0));
        txtAccNo3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAccNo3.setText("NAME:");
        txtAccNo3.setBorder(null);
        txtAccNo3.setOpaque(false);

        txtAccNo4.setEditable(false);
        txtAccNo4.setBackground(new java.awt.Color(255, 153, 0));
        txtAccNo4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAccNo4.setText("PHONE:");
        txtAccNo4.setBorder(null);
        txtAccNo4.setOpaque(false);

        javax.swing.GroupLayout import_homeLayout = new javax.swing.GroupLayout(import_home);
        import_home.setLayout(import_homeLayout);
        import_homeLayout.setHorizontalGroup(
            import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, import_homeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccNo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txtAccNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        import_homeLayout.setVerticalGroup(
            import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(import_homeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(import_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        main.add(import_home);
        import_home.setBounds(0, 0, 698, 340);

        import_withdraw.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("ENTER AMOUNT YOU WISH TO WITHDRAW");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);

        btnWithdraw.setText("WITHDRAW");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout import_withdrawLayout = new javax.swing.GroupLayout(import_withdraw);
        import_withdraw.setLayout(import_withdrawLayout);
        import_withdrawLayout.setHorizontalGroup(
            import_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_withdrawLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        import_withdrawLayout.setVerticalGroup(
            import_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(import_withdraw);
        import_withdraw.setBounds(0, 0, 700, 340);

        import_transfer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("FROM ACCOUNT");

        jLabel6.setText("TO ACCOUNT");

        jLabel7.setText("AMOUNT");

        frmAccount.setEnabled(false);

        btnsend.setText("SEND");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        btncancel.setText("CLEAR");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel9.setText("ENTER ACCOUNT NUMBER");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout import_transferLayout = new javax.swing.GroupLayout(import_transfer);
        import_transfer.setLayout(import_transferLayout);
        import_transferLayout.setHorizontalGroup(
            import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_transferLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(import_transferLayout.createSequentialGroup()
                            .addComponent(btnsend)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                            .addComponent(btncancel))
                        .addComponent(txtAmount)
                        .addComponent(toAccount)
                        .addComponent(frmAccount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        import_transferLayout.setVerticalGroup(
            import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_transferLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(frmAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(toAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(import_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsend)
                    .addComponent(btncancel))
                .addGap(51, 51, 51))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main.add(import_transfer);
        import_transfer.setBounds(0, 0, 700, 340);

        import_ministatement.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        area.setLineWrap(true);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        btnprint.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnprint.setText("PRINT STATEMENT");
        btnprint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout import_ministatementLayout = new javax.swing.GroupLayout(import_ministatement);
        import_ministatement.setLayout(import_ministatementLayout);
        import_ministatementLayout.setHorizontalGroup(
            import_ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(import_ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        import_ministatementLayout.setVerticalGroup(
            import_ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(import_ministatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(import_ministatement);
        import_ministatement.setBounds(0, 0, 700, 340);

        jMenu1.setText("Logout");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Change Pin");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(property_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(property_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
       
            home.setBackground(new Color(30,144,255));
        
        
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        if(!(active.equalsIgnoreCase("home"))){
        home.setBackground(new Color(0,102,102));
        }
    }//GEN-LAST:event_homeMouseExited

    private void withdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseEntered
        withdraw.setBackground(new Color(30,144,255));
    }//GEN-LAST:event_withdrawMouseEntered

    private void withdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMouseExited
         if(!(active.equalsIgnoreCase("withdraw"))){
        withdraw.setBackground(new Color(0,102,102));
        }
    }//GEN-LAST:event_withdrawMouseExited

    private void transferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseEntered
        transfer.setBackground(new Color(30,144,255));
    }//GEN-LAST:event_transferMouseEntered

    private void transferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMouseExited
        if(!(active.equalsIgnoreCase("transfer"))){
        transfer.setBackground(new Color(0,102,102));
        }
    }//GEN-LAST:event_transferMouseExited

    private void ministatementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ministatementMouseEntered
        ministatement.setBackground(new Color(30,144,255));
    }//GEN-LAST:event_ministatementMouseEntered

    private void ministatementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ministatementMouseExited
        if(!(active.equalsIgnoreCase("ministatement"))){
        ministatement.setBackground(new Color(0,102,102));
        }
    }//GEN-LAST:event_ministatementMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            main.removeAll();
            main.repaint();
            main.revalidate();
            //adding a panel
            main.add(import_home);
            main.repaint();
            main.revalidate();
            
        }catch(Exception e){
        
    }
    }//GEN-LAST:event_formWindowOpened

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        active = "home";
         home.setBackground(new Color(30,144,255));
         withdraw.setBackground(new Color(0,102,102));
         transfer.setBackground(new Color(0,102,102));
         ministatement.setBackground(new Color(0,102,102));
        try{
            main.removeAll();
            main.repaint();
            main.revalidate();
            //adding a panel
            main.add(import_home);
            main.repaint();
            main.revalidate();
            
        }catch(Exception e){
        
    }
    }//GEN-LAST:event_homeMousePressed

    private void withdrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawMousePressed
         active = "withdraw";
         withdraw.setBackground(new Color(30,144,255));
         home.setBackground(new Color(0,102,102));
         transfer.setBackground(new Color(0,102,102));
         ministatement.setBackground(new Color(0,102,102));
         
        try{
            main.removeAll();
            main.repaint();
            main.revalidate();
            //adding a panel
            main.add(import_withdraw);
            main.repaint();
            main.revalidate();
            
        }catch(Exception e){
        
    }
    }//GEN-LAST:event_withdrawMousePressed

    private void transferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferMousePressed
         active = "transfer";
         transfer.setBackground(new Color(30,144,255));
         home.setBackground(new Color(0,102,102));
         withdraw.setBackground(new Color(0,102,102));
         ministatement.setBackground(new Color(0,102,102));
         
        try{
            main.removeAll();
            main.repaint();
            main.revalidate();
            //adding a panel
            main.add(import_transfer);
            main.repaint();
            main.revalidate();
            
        }catch(Exception e){
        
    }
    }//GEN-LAST:event_transferMousePressed

    private void ministatementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ministatementMousePressed
         active = "ministatement";
         ministatement.setBackground(new Color(30,144,255));
         home.setBackground(new Color(0,102,102));
         withdraw.setBackground(new Color(0,102,102));
         transfer.setBackground(new Color(0,102,102));
         
        try{
            main.removeAll();
            main.repaint();
            main.revalidate();
            //adding a panel
            main.add(import_ministatement);
            main.repaint();
            main.revalidate();
            
        }catch(Exception e){
        
    }
                         area.setText("               UBIQUITTI BANK                \n");
        area.setText(area.getText() + "*********************************************\n");
        area.setText(area.getText() + "*               MINI STATEMENT              *\n");
        area.setText(area.getText() + "*********************************************\n");
        
        Date obj = new Date();
        
        String date = obj.toString();
        String RecAcc = null; 
        String recFN = null;
        String recSN = null;
        
        
        area.setText(area.getText() + "\n" + date + "\n"+ "\n");
        
        try{
                 conn = MySqlConnect.ConnectDB();
                 String sql3 = "Select to_account from transfer where f_account='"+l+"' order by date";
                 pst = conn.prepareStatement(sql3);
                 rs = pst.executeQuery();
                 
                 if(rs.next()){
                    RecAcc = rs.getString("to_account");
                 }
            }catch(SQLException e){
        }
        
                  
        
          try{
                 String sql4 = "Select * from account_details where accountNo='"+RecAcc+"'";      
                 pst = conn.prepareStatement(sql4);
                 rs = pst.executeQuery();
                 
                 if(rs.next()){
                  recFN = rs.getString("FirstName");
                  recSN = rs.getString("SecondName");
                                 
                 }
                 
        }catch(SQLException e){
            
        }
        
        try{
                 area.setText(area.getText() + "TRANSFERRALS\n");
                 
                 conn = MySqlConnect.ConnectDB();
                 String sql3 = "Select * from transfer where f_account='"+l+"'";
                 pst = conn.prepareStatement(sql3);
                 rs = pst.executeQuery();
                 
                                  
                 while(rs.next()){
                     String dateTime2 = rs.getString("date");
                     int trans = rs.getInt("amount");
                      
                     
                      area.setText(area.getText() + dateTime2 +"\t");
                      area.setText(area.getText() + "Sh." + trans +"\t");
                      area.setText(area.getText() + "To " + recFN + " " + recSN + " \n");      
                                                  
                
                }
                }catch(SQLException ex){
                    System.out.println(ex);
                }
        
       
                 
                try{
                    area.setText(area.getText() + "\nWITHDRWALS\n");
                    
                    conn = MySqlConnect.ConnectDB();
                    String sql2 = "Select * from withdrawal where accID='"+acid+"' and id>1";                   
                    pst = conn.prepareStatement(sql2);                    
                    rs = pst.executeQuery();
                    
                    while(rs.next()){
                        String dateTime = rs.getString("date");
                        int bal = rs.getInt("withdrawn");                        
                                              
                        area.setText(area.getText() + dateTime +"\t");
                        area.setText(area.getText() + "Sh." + bal +"\t" + "Withdrawn \n");
                                                
                    }
                }catch(SQLException e){
                    System.out.println(e);
                }
                
               
                
                   
       
    }//GEN-LAST:event_ministatementMousePressed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
       
       // String facc = frmAccount.getText();
        String toAcc = toAccount.getText();
        String amount= txtAmount.getText();
        int amo = Integer.parseInt(amount);
       
        
        int frid = 0;
        int toid = 0;
        String fname = null;
        String sname = null;
        
        if(toAcc.equals(l)){
            JOptionPane.showMessageDialog(null, "Use a different Account");
        }else{
        
        try{
                conn = MySqlConnect.ConnectDB();
                String sql = "Select * from account_details where accountNo='"+l+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                if(rs.next()){
                      frid = rs.getInt("id");
                      fname = rs.getString("FirstName");
                      sname = rs.getString("SecondName");
                      
                }
                
                }catch(SQLException ex){
                        System.out.println("Enter your valid acc no");
                        }
         try{
                conn = MySqlConnect.ConnectDB();
                String sql = "Select id from account_details where accountNo='"+toAcc+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                if(rs.next()){
                      toid = rs.getInt("id");
                      
                }
                
                }catch(SQLException ex){
                        System.out.println("Enter a valid ubiquitti acc no");
                        }
                
        try{
            conn = MySqlConnect.ConnectDB();
            
            //sender
            pst = conn.prepareStatement("update withdrawal set balance=balance-'"+amo+"' where accID='"+frid+"'");
            //pst.setInt(1, amo);           
            pst.executeUpdate();
            
            //receiver
            pst = conn.prepareStatement("update withdrawal set balance=balance+'"+amo+"' where accID='"+toid+"'");
            //pst1.setInt(1, amo);            
            pst.executeUpdate();
                        
            pst = conn.prepareStatement("INSERT INTO transfer(`f_account`, `to_account`, `amount`) VALUES (?,?,?)");            
            pst.setInt(3, amo);
            pst.setString(1, l);
            pst.setString(2, toAcc);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Amount transfered successfuly");
            
        } catch (SQLException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_btnsendActionPerformed

    
    
    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        Login lg = new Login();
        this.hide();
        lg.setVisible(true);
    }//GEN-LAST:event_jMenu1MousePressed

    private void btnBalanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMouseReleased
        txtBalance.setText(null);
    }//GEN-LAST:event_btnBalanceMouseReleased

    private void btnBalanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBalanceMousePressed
        try {
            
            
            conn = MySqlConnect.ConnectDB();
            String sql = "Select * from withdrawal where accID='"+acid+"' order by id desc limit 1";
             pst = conn.prepareStatement(sql);
             rs = pst.executeQuery();
            
            while(rs.next()){
                int balance = rs.getInt("balance");
                String bal = Integer.toString(balance);
                txtBalance.setText("Sh. " + bal);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBalanceMousePressed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        String a = txtwithdraw.getText();
        int wdr = 0;
        
        try{
            wdr = Integer.parseInt(a);
       
        if (wdr>50){
        if(JOptionPane.showConfirmDialog(this, "Do you wish to withdraw sh. " + a + " from your account?","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            try {
                                
                                
                    conn = MySqlConnect.ConnectDB();
                    String sql2 = "Select * from withdrawal where accID='"+acid+"' order by id desc limit 1";
                    pst = conn.prepareStatement(sql2);
                    rs = pst.executeQuery();
                    
                    if(rs.next()){
                        int bal = rs.getInt("balance");
                        
                        int d = Integer.parseInt(a);    //convert the withdraw value from string to integer 
                        
                        if(bal>d){
                        bal-=d; //balance = balance-d;
                        
                        String sql3 = "insert into withdrawal (balance, withdrawn, accID) values ('"+bal+"','"+d+"', '"+acid+"')";
                        pst = conn.prepareStatement(sql3);                       
                        pst.executeUpdate();
                        
                         JOptionPane.showMessageDialog(null, "A withdrawal of Sh. " + a + " has been confirmed.\n"
                                                        + "Your Current account balance is Sh. " + bal + ".");
                         
                        }else{
                            JOptionPane.showMessageDialog(null, "Failed!\n Account balance is too low");
                        }
                                               
                        txtwithdraw.setText(null);
                    }
                
                /*
                conn = MySqlConnect.ConnectDB();
                String sql = "Select balance from account_details where accountNo='"+l+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                while(rs.next()){
                    int balance = rs.getInt("balance");    //get current balance from db
                                      
                    int d = Integer.parseInt(a);    //convert the withdraw value from string to integer
                    
                    balance-=d; //balance = balance-d;
                                       
                    String sql3="update account_details set balance = '"+balance+"' where accountNo='"+l+"'";
                    Statement smt = conn.createStatement();
                    smt.executeUpdate(sql3);
                   
                    JOptionPane.showMessageDialog(null, "A withdrawal of Sh. " + a + " has been confirmed.\n"
                                                        + "Your Current account balance is Sh. " + balance + ".");
                    
                }
                */
                  
        } catch (SQLException ex) {
                Logger.getLogger(Navigation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
               JOptionPane.showMessageDialog(null, "WITHDRAWAL CANCELLED!!");
               txtwithdraw.setText(null);
       }
       }else{
            JOptionPane.showMessageDialog(null, "You cannot withdraw any amount less than Sh.50");
            txtwithdraw.setText(null);
        }
        
        }catch(NumberFormatException n){
            JOptionPane.showMessageDialog(null, "Enter a valid amount");
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try{
            area.print();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        Pin p = new Pin();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        frmAccount.setText(null);
        toAccount.setText(null);
        txtAmount.setText(null);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel TRANSFER;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsend;
    private javax.swing.JTextField frmAccount;
    private javax.swing.JPanel home;
    private javax.swing.JPanel import_home;
    private javax.swing.JPanel import_ministatement;
    private javax.swing.JPanel import_transfer;
    private javax.swing.JPanel import_withdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel ministatement;
    private javax.swing.JPanel property_panel;
    private javax.swing.JTextField toAccount;
    private javax.swing.JPanel transfer;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccNo2;
    private javax.swing.JTextField txtAccNo3;
    private javax.swing.JTextField txtAccNo4;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtwithdraw;
    private javax.swing.JPanel withdraw;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOperation(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
